### ISSUE TITLE
Theme since the update

### ISSUE THREAD

**Issue by timmy78** [jay-leno/yii2-codemirror#3]
Hi.

Where are listed the changes from the last update ?
I show that there are no more "htmlOptions". "theme" and "mode" are now in "pluginOptions".

I put the theme "solarized dark" but it doesn't appear ??

```
<?= $form->field($model, 'html')->widget(CodeMirror::className(), [
                    'pluginOptions' => [
                        'mode' => 'text/html',
                        "theme"=>'solarized dark'//solarized dark
                    ]
                ]) 
            ?>
```

Thanks

**Comment by jay-leno** [comment]
I apologize, it seems that the code written by the contributor to change 
over to working with the bower/codemirror release wasn't quite complete. 
Please revert to 1.1.1 for the time being until I have time to properly 
write that update. I will be removing 1.2.0 for now.

Jay Leno
